# Lesson #2
## Matrix & Arrays

In [17]:
import re

In [18]:
string_01 = "History is always written by the winners. hen two cultures clash, the loser is obliterated, and the winner writes the history books-books which glorify their own cause and disparage the conquered foe. As Napoleon once said, 'What is history, but a fable agreed upon?"

Find all words

In [19]:
re.findall('\w+', string_01)

['History',
 'is',
 'always',
 'written',
 'by',
 'the',
 'winners',
 'hen',
 'two',
 'cultures',
 'clash',
 'the',
 'loser',
 'is',
 'obliterated',
 'and',
 'the',
 'winner',
 'writes',
 'the',
 'history',
 'books',
 'books',
 'which',
 'glorify',
 'their',
 'own',
 'cause',
 'and',
 'disparage',
 'the',
 'conquered',
 'foe',
 'As',
 'Napoleon',
 'once',
 'said',
 'What',
 'is',
 'history',
 'but',
 'a',
 'fable',
 'agreed',
 'upon']

In [20]:
matrix = [ 
    [0,1,2,4,8], 
    [6,2,2,1,9], 
    [3,3,3,3,3], 
    [4,6,7,1,2], 
    [5,7,3,4,0] 
]

Sum of all numbers of the matrix

In [21]:
sum(sum(nums) for nums in matrix)

89

In [22]:
import numpy

In [23]:
numpy.sum(matrix)


89

Sum of all columns of the matrix

In [24]:
numpy.sum(matrix, axis=0)


array([18, 19, 17, 13, 22])

In [25]:
sum(numpy.sum(matrix, axis=0))

89

Sum of all rows of the matrix

In [26]:
numpy.sum(matrix, axis=1)

array([15, 20, 15, 20, 19])

Transposed matrix

In [28]:
list(zip(*matrix))

[(0, 6, 3, 4, 5),
 (1, 2, 3, 6, 7),
 (2, 2, 3, 7, 3),
 (4, 1, 3, 1, 4),
 (8, 9, 3, 2, 0)]

In [33]:
numpy.array(matrix).T

array([[0, 6, 3, 4, 5],
       [1, 2, 3, 6, 7],
       [2, 2, 3, 7, 3],
       [4, 1, 3, 1, 4],
       [8, 9, 3, 2, 0]])